#ifndef _LIBDEVICE_H_X86_
#define _LIBDEVICE_H_X86_

#include "libdevice/abs.h"
// #include "libdevice/atan2f.h"
// #include "libdevice/copysignf.h"
#include "libdevice/cosf.h"
// #include "libdevice/erfcf.h"
// #include "libdevice/erff_without_unary.h"
// #include "libdevice/erfinvf.h"
// #include "libdevice/expf.h"
// #include "libdevice/fabsf.h"
// #include "libdevice/fadd_rn.h"
// #include "libdevice/float2half_rn.h"
// #include "libdevice/float2int_rd.h"
// #include "libdevice/float2int_rn.h"
// #include "libdevice/float2int_rz.h"
// #include "libdevice/float_as_int.h"
// #include "libdevice/floorf.h"
// #include "libdevice/fmodf_without_unary.h"
// #include "libdevice/frcp_rd.h"
#include "libdevice/frcp_rd_without_unary.h"
// #include "libdevice/fsqrt_rd_without_unary.h"
// #include "libdevice/half2float.h"
// #include "libdevice/hypotf_without_unary.h"
// #include "libdevice/int2float_rn.h"
// #include "libdevice/int_as_float.h"
#include "libdevice/isinff.h"
// #include "libdevice/isnanf.h"
// #include "libdevice/lgammaf.h"
// #include "libdevice/log10f.h"
// #include "libdevice/log1pf.h"
// #include "libdevice/log2f_without_unary.h"
// #include "libdevice/logbf.h"
// #include "libdevice/logf.h"
// #include "libdevice/logf_without_unary.h"
// #include "libdevice/powf.h"
// #include "libdevice/powf_without_unary.h"
// #include "libdevice/roundf.h"
// #include "libdevice/rsqrtf_without_unary.h"
// #include "libdevice/sinf.h"
// #include "libdevice/sinhf_without_unary.h"
// #include "libdevice/sqrtf.h"
// #include "libdevice/tanf.h"
// #include "libdevice/tanhf_without_unary.h"
// #include "libdevice/truncf.h"
// #include "libdevice/umax.h"
// #include "libdevice/umin.h"

#endif

